//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugAlarm.Resx {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("DrugAlarm.Resx.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string List_AddList {
            get {
                return ResourceManager.GetString("List_AddList", resourceCulture);
            }
        }
        
        internal static string List_DeleteMessage {
            get {
                return ResourceManager.GetString("List_DeleteMessage", resourceCulture);
            }
        }
        
        internal static string List_DrugMedicineMessage {
            get {
                return ResourceManager.GetString("List_DrugMedicineMessage", resourceCulture);
            }
        }
        
        internal static string List_Menu_Delete {
            get {
                return ResourceManager.GetString("List_Menu_Delete", resourceCulture);
            }
        }
        
        internal static string List_Menu_Drug {
            get {
                return ResourceManager.GetString("List_Menu_Drug", resourceCulture);
            }
        }
        
        internal static string List_Menu_Edit {
            get {
                return ResourceManager.GetString("List_Menu_Edit", resourceCulture);
            }
        }
        
        internal static string List_Title {
            get {
                return ResourceManager.GetString("List_Title", resourceCulture);
            }
        }
        
        internal static string List_Setting {
            get {
                return ResourceManager.GetString("List_Setting", resourceCulture);
            }
        }
    }
}
