//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugAlarm.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrugAlarm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_Setting {
            get {
                return ResourceManager.GetString("List_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お薬一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_Title {
            get {
                return ResourceManager.GetString("List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   食後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_AfterMeals {
            get {
                return ResourceManager.GetString("Setting_AfterMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_AfterMinute {
            get {
                return ResourceManager.GetString("Setting_AfterMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   食前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_BeforeMeals {
            get {
                return ResourceManager.GetString("Setting_BeforeMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_BeforeMinute {
            get {
                return ResourceManager.GetString("Setting_BeforeMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   就寝前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_BeforeSleep {
            get {
                return ResourceManager.GetString("Setting_BeforeSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   朝食時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Breakfast {
            get {
                return ResourceManager.GetString("Setting_Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   夕食時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Dinner {
            get {
                return ResourceManager.GetString("Setting_Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_InputAlarm {
            get {
                return ResourceManager.GetString("Setting_InputAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   昼食時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Lunch {
            get {
                return ResourceManager.GetString("Setting_Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   薬残量お知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Prescript {
            get {
                return ResourceManager.GetString("Setting_Prescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Realarm {
            get {
                return ResourceManager.GetString("Setting_Realarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Remaining {
            get {
                return ResourceManager.GetString("Setting_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   就寝時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Sleep {
            get {
                return ResourceManager.GetString("Setting_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Title {
            get {
                return ResourceManager.GetString("Setting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   錠 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Unit {
            get {
                return ResourceManager.GetString("Setting_Unit", resourceCulture);
            }
        }
    }
}
