//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugAlarm.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DrugAlarm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   完了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alarm_Button_OK {
            get {
                return ResourceManager.GetString("Alarm_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   あとで に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alarm_Button_Realarm {
            get {
                return ResourceManager.GetString("Alarm_Button_Realarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お薬の時間です に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Alarm_Title {
            get {
                return ResourceManager.GetString("Alarm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   多重起動防止 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string App_MutexMessage {
            get {
                return ResourceManager.GetString("App_MutexMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   食後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_AfterMeals {
            get {
                return ResourceManager.GetString("Detail_AfterMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   薬残量お知らせは_ALARMVOLUME_錠以下で入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_AlarmVolumeOverMessage {
            get {
                return ResourceManager.GetString("Detail_AlarmVolumeOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   食前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_BeforeMeals {
            get {
                return ResourceManager.GetString("Detail_BeforeMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   食間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_BetweenMeals {
            get {
                return ResourceManager.GetString("Detail_BetweenMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集中のデータを破棄しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_CancelMessage {
            get {
                return ResourceManager.GetString("Detail_CancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日時指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_DateSpecified {
            get {
                return ResourceManager.GetString("Detail_DateSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   夕 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_Dinner {
            get {
                return ResourceManager.GetString("Detail_Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   昼 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_Lunch {
            get {
                return ResourceManager.GetString("Detail_Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   朝 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_Morning {
            get {
                return ResourceManager.GetString("Detail_Morning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_Name {
            get {
                return ResourceManager.GetString("Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   頓服 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_Potions {
            get {
                return ResourceManager.GetString("Detail_Potions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   薬残量お知らせ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_Prescript {
            get {
                return ResourceManager.GetString("Detail_Prescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   残り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_Remaining {
            get {
                return ResourceManager.GetString("Detail_Remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   備考 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_Remarks {
            get {
                return ResourceManager.GetString("Detail_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _DRUG_を保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_SaveMessage {
            get {
                return ResourceManager.GetString("Detail_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   就寝前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_Sleep {
            get {
                return ResourceManager.GetString("Detail_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間毎 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_Time {
            get {
                return ResourceManager.GetString("Detail_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間指定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_TimeSpecified {
            get {
                return ResourceManager.GetString("Detail_TimeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   服用時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_Timing {
            get {
                return ResourceManager.GetString("Detail_Timing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お薬の内容 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_Title {
            get {
                return ResourceManager.GetString("Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処方量は_TOTALVOLUME_錠以下で入力してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_TotalVolumeOverMessage {
            get {
                return ResourceManager.GetString("Detail_TotalVolumeOverMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   錠 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_Unit {
            get {
                return ResourceManager.GetString("Detail_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   処方量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Detail_Volume {
            get {
                return ResourceManager.GetString("Detail_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   パラメータファイルを保存するフォルダを指定してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string FolderDialog_Title {
            get {
                return ResourceManager.GetString("FolderDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お薬が切れそうです に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Information_Title {
            get {
                return ResourceManager.GetString("Information_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   + 新規追加 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_AddList {
            get {
                return ResourceManager.GetString("List_AddList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _DRUG_を削除しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_DeleteMessage {
            get {
                return ResourceManager.GetString("List_DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _DRUG_を服用しました に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_DrugMedicineMessage {
            get {
                return ResourceManager.GetString("List_DrugMedicineMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_Menu_Delete {
            get {
                return ResourceManager.GetString("List_Menu_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   頓服服用 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_Menu_Drug {
            get {
                return ResourceManager.GetString("List_Menu_Drug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_Menu_Edit {
            get {
                return ResourceManager.GetString("List_Menu_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_Setting {
            get {
                return ResourceManager.GetString("List_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   お薬一覧 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string List_Title {
            get {
                return ResourceManager.GetString("List_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   終了 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_Exit {
            get {
                return ResourceManager.GetString("Menu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   一覧表示 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Menu_ShowList {
            get {
                return ResourceManager.GetString("Menu_ShowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   食後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Parameter_Timing_After {
            get {
                return ResourceManager.GetString("Parameter_Timing_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   毎 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Parameter_Timing_Always {
            get {
                return ResourceManager.GetString("Parameter_Timing_Always", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _yyyy/MM/dd HH:mm_ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Parameter_Timing_Appoint {
            get {
                return ResourceManager.GetString("Parameter_Timing_Appoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   食前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Parameter_Timing_Before {
            get {
                return ResourceManager.GetString("Parameter_Timing_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   食間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Parameter_Timing_Between {
            get {
                return ResourceManager.GetString("Parameter_Timing_Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   朝 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Parameter_Timing_Breakfast {
            get {
                return ResourceManager.GetString("Parameter_Timing_Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   夕 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Parameter_Timing_Dinner {
            get {
                return ResourceManager.GetString("Parameter_Timing_Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _n_時間毎 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Parameter_Timing_Each {
            get {
                return ResourceManager.GetString("Parameter_Timing_Each", resourceCulture);
            }
        }
        
        /// <summary>
        ///   昼 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Parameter_Timing_Lunch {
            get {
                return ResourceManager.GetString("Parameter_Timing_Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   就寝前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Parameter_Timing_Sleep {
            get {
                return ResourceManager.GetString("Parameter_Timing_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   頓服 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Parameter_Timing_ToBeTaken {
            get {
                return ResourceManager.GetString("Parameter_Timing_ToBeTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Realarm_Button_OK {
            get {
                return ResourceManager.GetString("Realarm_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分後に通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Realarm_Message {
            get {
                return ResourceManager.GetString("Realarm_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Realarm_Title {
            get {
                return ResourceManager.GetString("Realarm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   食後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_AfterMeals {
            get {
                return ResourceManager.GetString("Setting_AfterMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分後 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_AfterMinute {
            get {
                return ResourceManager.GetString("Setting_AfterMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   食前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_BeforeMeals {
            get {
                return ResourceManager.GetString("Setting_BeforeMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   分前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_BeforeMinute {
            get {
                return ResourceManager.GetString("Setting_BeforeMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   就寝前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_BeforeSleep {
            get {
                return ResourceManager.GetString("Setting_BeforeSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   朝食時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Breakfast {
            get {
                return ResourceManager.GetString("Setting_Breakfast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   編集中のデータを破棄しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_CancelMessage {
            get {
                return ResourceManager.GetString("Setting_CancelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   夕食時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Dinner {
            get {
                return ResourceManager.GetString("Setting_Dinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   アラーム設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_InputAlarm {
            get {
                return ResourceManager.GetString("Setting_InputAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   昼食時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Lunch {
            get {
                return ResourceManager.GetString("Setting_Lunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   再通知 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Realarm {
            get {
                return ResourceManager.GetString("Setting_Realarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定を保存しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_SaveMessage {
            get {
                return ResourceManager.GetString("Setting_SaveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   就寝時間 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Sleep {
            get {
                return ResourceManager.GetString("Setting_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Title {
            get {
                return ResourceManager.GetString("Setting_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   錠 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Setting_Unit {
            get {
                return ResourceManager.GetString("Setting_Unit", resourceCulture);
            }
        }
    }
}
